project:
  type: website
  output-dir: docs

website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: portfolio.qmd
        text: Portfolio
      - href: Sofija_Kaluderovic_CV.pdf
        text: CV 
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

